[theme]
base = "light"  # Change to "dark" if you prefer
primaryColor = "#0052cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif"


[server]
headless = true
enableCORS = false
port = 8501
enableXsrfProtection = false
script = "confcall.py"  # <-- change to your actual file name
